# Move validation of the v1 version to the top-level, and remove validation from the v1beta1 version.
# This is the behaviour intended from using controller-tools crd:trivialVersions=true flag,
# which currently does not work as expected.
# See https://github.com/kubernetes-sigs/controller-tools/issues/349.
# TODO: remove once fixed in controller-tools
#- op: remove
#  path: /spec/versions/1/schema
## Using `kubectl apply` stores the complete CRD file as an annotation,
# which may be too big for the annotations size limit.
# One way to mitigate this problem is to remove the (huge) podTemplate properties from the CRD.
# It also avoids the problem of having any k8s-version specific field in the Pod schema,
# that would maybe not match the user's k8s version.
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/nodeSets/items/properties/podTemplate/properties
- op: remove
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/nodeSets/items/properties/podTemplate/properties