## This constraint ensures that
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAutomountServiceAccountTokenPod
metadata:
  name: automount-sa-token-pod
spec:
  match:
    ## All namespaces whose name ends with '-system' and the local-volume provisioner
    excludedNamespaces: ["*-system", "default", "local-path-storage"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        ## Only Agent and Beat are allowed to automount the service account token in order to access the K8S API.
        - { key: common.k8s.elastic.co/type, operator: NotIn, values: [ beat, agent ] }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: must-run-as-non-root
spec:
  match:
    ## Nothing is expected to run as root on the cluster except Pods in kube-system and the local-volume provisioner
    excludedNamespaces: ["*-system", "default", "local-path-storage"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    labelSelector:
      matchExpressions:
        ## Only Agent and Beat are allowed to run as root
        - { key: common.k8s.elastic.co/type, operator: NotIn, values: [ beat, agent ] }
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot
