apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/open-policy-agent/gatekeeper-library/library/general/automount-serviceaccount-token
- github.com/open-policy-agent/gatekeeper-library/library/pod-security-policy/users

