// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

package common

import (
	"sigs.k8s.io/controller-runtime/pkg/client"

	commonv1 "github.com/elastic/cloud-on-k8s/v3/pkg/apis/common/v1"
	"github.com/elastic/cloud-on-k8s/v3/pkg/controller/common/hash"
	"github.com/elastic/cloud-on-k8s/v3/pkg/utils/optional"
)

const (
	// ElasticsearchContainerName is the name of the Elasticsearch container in pods.
	ElasticsearchContainerName = "elasticsearch"
)

// ElasticsearchHealth is the health of the cluster as returned by the health API.
type ElasticsearchHealth string

// Possible traffic light states Elasticsearch health can have.
const (
	ElasticsearchRedHealth     ElasticsearchHealth = "red"
	ElasticsearchYellowHealth  ElasticsearchHealth = "yellow"
	ElasticsearchGreenHealth   ElasticsearchHealth = "green"
	ElasticsearchUnknownHealth ElasticsearchHealth = "unknown"
)

var elasticsearchHealthOrder = map[ElasticsearchHealth]int{
	ElasticsearchRedHealth:    1,
	ElasticsearchYellowHealth: 2,
	ElasticsearchGreenHealth:  3,
}

// Less for ElasticsearchHealth means green > yellow > red
func (h ElasticsearchHealth) Less(other ElasticsearchHealth) bool {
	l := elasticsearchHealthOrder[h]
	r := elasticsearchHealthOrder[other]
	// 0 is not found/unknown and less is not defined for that
	return l != 0 && r != 0 && l < r
}

// ElasticsearchOrchestrationPhase is the phase Elasticsearch is in from the controller point of view.
type ElasticsearchOrchestrationPhase string

const (
	// ElasticsearchReadyPhase is operating at the desired spec.
	ElasticsearchReadyPhase ElasticsearchOrchestrationPhase = "Ready"
	// ElasticsearchApplyingChangesPhase controller is working towards a desired state, cluster can be unavailable.
	ElasticsearchApplyingChangesPhase ElasticsearchOrchestrationPhase = "ApplyingChanges"
	// ElasticsearchMigratingDataPhase Elasticsearch is currently migrating data to another node.
	ElasticsearchMigratingDataPhase ElasticsearchOrchestrationPhase = "MigratingData"
	// ElasticsearchNodeShutdownStalledPhase Elasticsearch cannot make progress with a node shutdown during downscale or rolling upgrade.
	ElasticsearchNodeShutdownStalledPhase ElasticsearchOrchestrationPhase = "Stalled"
	// ElasticsearchResourceInvalid is marking a resource as invalid, should never happen if admission control is installed correctly.
	ElasticsearchResourceInvalid ElasticsearchOrchestrationPhase = "Invalid"
)

// RemoteClusterServer defines the configuration for the remote cluster server.
type RemoteClusterServer struct {
	// +kubebuilder:validation:Optional
	Enabled bool `json:"enabled,omitempty"`
	// Service defines the template for the remote cluster server Service object.
	Service commonv1.ServiceTemplate `json:"service,omitempty"`
}

// TransportConfig holds the transport layer settings for Elasticsearch.
type TransportConfig struct {
	// Service defines the template for the associated Kubernetes Service object.
	Service commonv1.ServiceTemplate `json:"service,omitempty"`
	// TLS defines options for configuring TLS on the transport layer.
	TLS TransportTLSOptions `json:"tls,omitempty"`
}

// TransportTLSOptions holds TLS configuration options for the transport layer.
type TransportTLSOptions struct {
	// OtherNameSuffix when defined will be prefixed with the Pod name and used as the common name,
	// and the first DNSName, as well as an OtherName required by Elasticsearch in the Subject Alternative Name
	// extension of each Elasticsearch node's transport TLS certificate.
	// Example: if set to "node.cluster.local", the generated certificate will have its otherName set to "<pod_name>.node.cluster.local".
	OtherNameSuffix string `json:"otherNameSuffix,omitempty"`
	// SubjectAlternativeNames is a list of SANs to include in the generated node transport TLS certificates.
	SubjectAlternativeNames []commonv1.SubjectAlternativeName `json:"subjectAltNames,omitempty"`
	// Certificate is a reference to a Kubernetes secret that contains the CA certificate
	// and private key for generating node certificates.
	// The referenced secret should contain the following:
	//
	// - `ca.crt`: The CA certificate in PEM format.
	// - `ca.key`: The private key for the CA certificate in PEM format.
	Certificate commonv1.SecretRef `json:"certificate,omitempty"`
	// CertificateAuthorities is a reference to a config map that contains one or more x509 certificates for
	// trusted authorities in PEM format. The certificates need to be in a file called `ca.crt`.
	CertificateAuthorities commonv1.ConfigMapRef `json:"certificateAuthorities,omitempty"`
	// SelfSignedCertificates allows configuring the self-signed certificate generated by the operator.
	SelfSignedCertificates *SelfSignedTransportCertificates `json:"selfSignedCertificates,omitempty"`
}

// SelfSignedEnabled returns true if self-signed certificates are enabled.
func (tto TransportTLSOptions) SelfSignedEnabled() bool {
	return tto.SelfSignedCertificates == nil || !tto.SelfSignedCertificates.Disabled
}

// UserDefinedCA returns true if a user-defined CA is configured.
func (tto TransportTLSOptions) UserDefinedCA() bool {
	return tto.Certificate.SecretName != ""
}

// SelfSignedTransportCertificates holds configuration for the self-signed certificates generated by the operator.
type SelfSignedTransportCertificates struct {
	// Disabled indicates that provisioning of the self-signed certificates should be disabled.
	Disabled bool `json:"disabled,omitempty"`
}

// Auth contains user authentication and authorization security settings for Elasticsearch.
type Auth struct {
	// Roles to propagate to the Elasticsearch cluster.
	Roles []RoleSource `json:"roles,omitempty"`
	// FileRealm to propagate to the Elasticsearch cluster.
	FileRealm []FileRealmSource `json:"fileRealm,omitempty"`
	// DisableElasticUser disables the default elastic user that is created by ECK.
	DisableElasticUser bool `json:"disableElasticUser,omitempty"`
}

// RoleSource references roles to create in the Elasticsearch cluster.
type RoleSource struct {
	// SecretName references a Kubernetes secret in the same namespace as the Elasticsearch resource.
	// Multiple roles can be specified in a Kubernetes secret, under a single "roles.yml" entry.
	// The secret value must match the expected file-based specification as described in
	// https://www.elastic.co/guide/en/elasticsearch/reference/current/defining-roles.html#roles-management-file.
	//
	// Example:
	// ---
	// kind: Secret
	// apiVersion: v1
	// metadata:
	// 	name: my-roles
	// stringData:
	//  roles.yml: |-
	//    click_admins:
	//      run_as: [ 'clicks_watcher_1' ]
	//   	cluster: [ 'monitor' ]
	//   	indices:
	//   	- names: [ 'events-*' ]
	//   	  privileges: [ 'read' ]
	//   	  field_security:
	//   		grant: ['category', '@timestamp', 'message' ]
	//   	  query: '{"match": {"category": "click"}}'
	//    another_role:
	//      cluster: [ 'all' ]
	// ---
	commonv1.SecretRef `json:",inline"`
}

// FileRealmSource references users to create in the Elasticsearch cluster.
type FileRealmSource struct {
	// SecretName references a Kubernetes secret in the same namespace as the Elasticsearch resource.
	// Multiple users and their roles mapping can be specified in a Kubernetes secret.
	// The secret should contain 2 entries:
	// - users: contain all users and the hash of their password (https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#password-hashing-algorithms)
	// - users_roles: contain the role to users mapping
	// The format of those 2 entries must correspond to the expected file realm format, as specified in Elasticsearch
	// documentation: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/file-realm.html#file-realm-configuration.
	//
	// Example:
	// ---
	// # File realm in ES format (from the CLI or manually assembled)
	// kind: Secret
	// apiVersion: v1
	// metadata:
	//   name: my-filerealm
	// stringData:
	//   users: |-
	//     rdeniro:$2a$10$BBJ/ILiyJ1eBTYoRKxkqbuDEdYECplvxnqQ47uiowE7yGqvCEgj9W
	//     alpacino:$2a$10$cNwHnElYiMYZ/T3K4PvzGeJ1KbpXZp2PfoQD.gfaVdImnHOwIuBKS
	//     jacknich:{PBKDF2}50000$z1CLJt0MEFjkIK5iEfgvfnA6xq7lF25uasspsTKSo5Q=$XxCVLbaKDimOdyWgLCLJiyoiWpA/XDMe/xtVgn1r5Sg=
	//   users_roles: |-
	//     admin:rdeniro
	//     power_user:alpacino,jacknich
	//     user:jacknich
	// ---
	commonv1.SecretRef `json:",inline"`
}

// RemoteCluster declares a remote Elasticsearch cluster connection.
type RemoteCluster struct {
	// Name is the name of the remote cluster as it is set in the Elasticsearch settings.
	// The name is expected to be unique for each remote clusters.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// ElasticsearchRef is a reference to an Elasticsearch cluster running within the same k8s cluster.
	// Supports both stateful Elasticsearch and stateless ElasticsearchStateless resources via the Kind field.
	ElasticsearchRef commonv1.LocalElasticsearchRef `json:"elasticsearchRef,omitempty"`

	// APIKey can be used to enable remote cluster access using Cross-Cluster API keys: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-cross-cluster-api-key.html
	// +kubebuilder:validation:Optional
	APIKey *RemoteClusterAPIKey `json:"apiKey,omitempty"`

	// TODO: Allow the user to specify some options (transport.compress, transport.ping_schedule)
}

// ConfigHash returns a hash of the RemoteCluster configuration for change detection.
func (r RemoteCluster) ConfigHash() string {
	return hash.HashObject(r)
}

// RemoteClusterAPIKey defines a remote cluster API Key.
type RemoteClusterAPIKey struct {
	// Access is the name of the API Key. It is automatically generated if not set or empty.
	// +kubebuilder:validation:Required
	Access RemoteClusterAccess `json:"access,omitempty"`
}

// RemoteClusterAccess models the API key specification as documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-cross-cluster-api-key.html
type RemoteClusterAccess struct {
	// +kubebuilder:validation:Optional
	Search *Search `json:"search,omitempty"`
	// +kubebuilder:validation:Optional
	Replication *Replication `json:"replication,omitempty"`
}

// Search defines search access for remote cluster API keys.
type Search struct {
	// +kubebuilder:validation:Required
	Names []string `json:"names,omitempty"`

	// +kubebuilder:validation:Optional
	FieldSecurity *FieldSecurity `json:"field_security,omitempty"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Query *commonv1.Config `json:"query,omitempty"`

	// +kubebuilder:validation:Optional
	AllowRestrictedIndices bool `json:"allow_restricted_indices,omitempty"`
}

// FieldSecurity defines field-level security for search access.
type FieldSecurity struct {
	Grant  []string `json:"grant"`
	Except []string `json:"except"`
}

// Replication defines replication access for remote cluster API keys.
type Replication struct {
	// +kubebuilder:validation:Required
	Names []string `json:"names,omitempty"`
}

// ElasticsearchCluster is an interface that defines common accessors for Elasticsearch cluster resources.
// Both stateful Elasticsearch and stateless ElasticsearchStateless implement this interface.
// This interface also satisfies the HasKeystore interface from the keystore package.
// +kubebuilder:object:generate=false
type ElasticsearchCluster interface {
	// client.Object embeds metav1.Object and runtime.Object, providing access to
	// Kubernetes object metadata (GetName, GetNamespace, etc.) and allowing
	// direct use with the controller-runtime client.
	client.Object

	// GetVersion returns the Elasticsearch version.
	GetVersion() string
	// GetImage returns the Elasticsearch Docker image.
	GetImage() string
	// GetHTTP returns the HTTP layer configuration.
	GetHTTP() commonv1.HTTPConfig
	// GetTransport returns the transport layer configuration.
	GetTransport() TransportConfig
	// GetAuth returns the authentication and authorization settings.
	GetAuth() Auth
	// GetSecureSettings returns the list of secure settings secret sources.
	GetSecureSettings() []commonv1.SecretSource
	// SecureSettings returns the list of secure settings secret sources.
	// This method is required to satisfy the HasKeystore interface.
	SecureSettings() []commonv1.SecretSource
	// GetServiceAccountName returns the service account name.
	GetServiceAccountName() string
	// GetRemoteClusterServer returns the remote cluster server configuration.
	GetRemoteClusterServer() RemoteClusterServer
	// GetRemoteClusters returns the list of remote cluster configurations.
	GetRemoteClusters() []RemoteCluster
	// SupportsRemoteClusterAPIKeys returns true if this cluster supports connecting to a remote cluster using API keys.
	// Returns nil if the support status cannot be determined yet (e.g., version not available).
	SupportsRemoteClusterAPIKeys() (*optional.Bool, error)
	// IsStateless returns true if this is a stateless Elasticsearch cluster.
	IsStateless() bool
	// DownwardNodeLabels returns the set of expected node labels to be copied as annotations on the Elasticsearch Pods.
	DownwardNodeLabels() []string
	// HasDownwardNodeLabels returns true if some node labels are expected on the Elasticsearch Pods.
	HasDownwardNodeLabels() bool
	// IsConfiguredToAllowDowngrades returns true if the cluster allows downgrades.
	IsConfiguredToAllowDowngrades() bool
	// GetAssociations returns the list of associations for this Elasticsearch cluster.
	GetAssociations() []commonv1.Association
	// GetIdentityLabels returns the identity labels for the cluster.
	// Required to satisfy commonv1.HasIdentityLabels interface.
	GetIdentityLabels() map[string]string
	// GetMonitoringMetricsRefs returns the list of Elasticsearch refs for metrics monitoring.
	GetMonitoringMetricsRefs() []commonv1.ElasticsearchRef
	// GetMonitoringLogsRefs returns the list of Elasticsearch refs for logs monitoring.
	GetMonitoringLogsRefs() []commonv1.ElasticsearchRef
	// MonitoringAssociation returns the monitoring association for the given selector.
	MonitoringAssociation(ref commonv1.ObjectSelector) commonv1.Association
}

// HasRemoteClusterAPIKey returns true if this cluster is connecting to a remote cluster using API keys.
func HasRemoteClusterAPIKey(es ElasticsearchCluster) bool {
	if es == nil {
		return false
	}
	for _, remoteCluster := range es.GetRemoteClusters() {
		if remoteCluster.APIKey != nil {
			return true
		}
	}
	return false
}

// RemoteClustersCount returns the number of remote clusters using only certificates and API keys.
func RemoteClustersCount(es ElasticsearchCluster) (withoutAPIKeys, withAPIKeys int32) {
	if es == nil {
		return 0, 0
	}
	for _, remoteCluster := range es.GetRemoteClusters() {
		if remoteCluster.APIKey == nil {
			withoutAPIKeys++
			continue
		}
		withAPIKeys++
	}
	return withoutAPIKeys, withAPIKeys
}
