//go:build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	"github.com/elastic/cloud-on-k8s/v3/pkg/apis/common/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RoleSource, len(*in))
		copy(*out, *in)
	}
	if in.FileRealm != nil {
		in, out := &in.FileRealm, &out.FileRealm
		*out = make([]FileRealmSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldSecurity) DeepCopyInto(out *FieldSecurity) {
	*out = *in
	if in.Grant != nil {
		in, out := &in.Grant, &out.Grant
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldSecurity.
func (in *FieldSecurity) DeepCopy() *FieldSecurity {
	if in == nil {
		return nil
	}
	out := new(FieldSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRealmSource) DeepCopyInto(out *FileRealmSource) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRealmSource.
func (in *FileRealmSource) DeepCopy() *FileRealmSource {
	if in == nil {
		return nil
	}
	out := new(FileRealmSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCluster) DeepCopyInto(out *RemoteCluster) {
	*out = *in
	out.ElasticsearchRef = in.ElasticsearchRef
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(RemoteClusterAPIKey)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCluster.
func (in *RemoteCluster) DeepCopy() *RemoteCluster {
	if in == nil {
		return nil
	}
	out := new(RemoteCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterAPIKey) DeepCopyInto(out *RemoteClusterAPIKey) {
	*out = *in
	in.Access.DeepCopyInto(&out.Access)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterAPIKey.
func (in *RemoteClusterAPIKey) DeepCopy() *RemoteClusterAPIKey {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterAPIKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterAccess) DeepCopyInto(out *RemoteClusterAccess) {
	*out = *in
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(Search)
		(*in).DeepCopyInto(*out)
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(Replication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterAccess.
func (in *RemoteClusterAccess) DeepCopy() *RemoteClusterAccess {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterServer) DeepCopyInto(out *RemoteClusterServer) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterServer.
func (in *RemoteClusterServer) DeepCopy() *RemoteClusterServer {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replication) DeepCopyInto(out *Replication) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replication.
func (in *Replication) DeepCopy() *Replication {
	if in == nil {
		return nil
	}
	out := new(Replication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleSource) DeepCopyInto(out *RoleSource) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleSource.
func (in *RoleSource) DeepCopy() *RoleSource {
	if in == nil {
		return nil
	}
	out := new(RoleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Search) DeepCopyInto(out *Search) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FieldSecurity != nil {
		in, out := &in.FieldSecurity, &out.FieldSecurity
		*out = new(FieldSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Search.
func (in *Search) DeepCopy() *Search {
	if in == nil {
		return nil
	}
	out := new(Search)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfSignedTransportCertificates) DeepCopyInto(out *SelfSignedTransportCertificates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfSignedTransportCertificates.
func (in *SelfSignedTransportCertificates) DeepCopy() *SelfSignedTransportCertificates {
	if in == nil {
		return nil
	}
	out := new(SelfSignedTransportCertificates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportConfig) DeepCopyInto(out *TransportConfig) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportConfig.
func (in *TransportConfig) DeepCopy() *TransportConfig {
	if in == nil {
		return nil
	}
	out := new(TransportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportTLSOptions) DeepCopyInto(out *TransportTLSOptions) {
	*out = *in
	if in.SubjectAlternativeNames != nil {
		in, out := &in.SubjectAlternativeNames, &out.SubjectAlternativeNames
		*out = make([]v1.SubjectAlternativeName, len(*in))
		copy(*out, *in)
	}
	out.Certificate = in.Certificate
	out.CertificateAuthorities = in.CertificateAuthorities
	if in.SelfSignedCertificates != nil {
		in, out := &in.SelfSignedCertificates, &out.SelfSignedCertificates
		*out = new(SelfSignedTransportCertificates)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportTLSOptions.
func (in *TransportTLSOptions) DeepCopy() *TransportTLSOptions {
	if in == nil {
		return nil
	}
	out := new(TransportTLSOptions)
	in.DeepCopyInto(out)
	return out
}
