//go:build !ignore_autogenerated

// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/elastic/cloud-on-k8s/v3/pkg/apis/common/v1"
	"github.com/elastic/cloud-on-k8s/v3/pkg/apis/elasticsearch/common"
	appsv1 "k8s.io/api/apps/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchStateless) DeepCopyInto(out *ElasticsearchStateless) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.AssocConfs != nil {
		in, out := &in.AssocConfs, &out.AssocConfs
		*out = make(map[v1.ObjectSelector]v1.AssociationConf, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchStateless.
func (in *ElasticsearchStateless) DeepCopy() *ElasticsearchStateless {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchStateless)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticsearchStateless) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchStatelessList) DeepCopyInto(out *ElasticsearchStatelessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticsearchStateless, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchStatelessList.
func (in *ElasticsearchStatelessList) DeepCopy() *ElasticsearchStatelessList {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchStatelessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticsearchStatelessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchStatelessSpec) DeepCopyInto(out *ElasticsearchStatelessSpec) {
	*out = *in
	in.RemoteClusterServer.DeepCopyInto(&out.RemoteClusterServer)
	out.ObjectStore = in.ObjectStore
	in.Tiers.DeepCopyInto(&out.Tiers)
	in.HTTP.DeepCopyInto(&out.HTTP)
	in.Transport.DeepCopyInto(&out.Transport)
	in.Auth.DeepCopyInto(&out.Auth)
	if in.SecureSettings != nil {
		in, out := &in.SecureSettings, &out.SecureSettings
		*out = make([]v1.SecretSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RemoteClusters != nil {
		in, out := &in.RemoteClusters, &out.RemoteClusters
		*out = make([]common.RemoteCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Monitoring.DeepCopyInto(&out.Monitoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchStatelessSpec.
func (in *ElasticsearchStatelessSpec) DeepCopy() *ElasticsearchStatelessSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchStatelessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchStatelessStatus) DeepCopyInto(out *ElasticsearchStatelessStatus) {
	*out = *in
	if in.IndexTierStatus != nil {
		in, out := &in.IndexTierStatus, &out.IndexTierStatus
		*out = new(TierStatus)
		**out = **in
	}
	if in.SearchTierStatus != nil {
		in, out := &in.SearchTierStatus, &out.SearchTierStatus
		*out = new(TierStatus)
		**out = **in
	}
	if in.MLTierStatus != nil {
		in, out := &in.MLTierStatus, &out.MLTierStatus
		*out = new(TierStatus)
		**out = **in
	}
	if in.MonitoringAssociationStatus != nil {
		in, out := &in.MonitoringAssociationStatus, &out.MonitoringAssociationStatus
		*out = make(v1.AssociationStatusMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchStatelessStatus.
func (in *ElasticsearchStatelessStatus) DeepCopy() *ElasticsearchStatelessStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchStatelessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchStatelessTiers) DeepCopyInto(out *ElasticsearchStatelessTiers) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(TierSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(TierSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ML != nil {
		in, out := &in.ML, &out.ML
		*out = new(TierSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchStatelessTiers.
func (in *ElasticsearchStatelessTiers) DeepCopy() *ElasticsearchStatelessTiers {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchStatelessTiers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EssMonitoringAssociation) DeepCopyInto(out *EssMonitoringAssociation) {
	*out = *in
	if in.ElasticsearchStateless != nil {
		in, out := &in.ElasticsearchStateless, &out.ElasticsearchStateless
		*out = new(ElasticsearchStateless)
		(*in).DeepCopyInto(*out)
	}
	out.ref = in.ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EssMonitoringAssociation.
func (in *EssMonitoringAssociation) DeepCopy() *EssMonitoringAssociation {
	if in == nil {
		return nil
	}
	out := new(EssMonitoringAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreConfig) DeepCopyInto(out *ObjectStoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreConfig.
func (in *ObjectStoreConfig) DeepCopy() *ObjectStoreConfig {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleMetadata) DeepCopyInto(out *SimpleMetadata) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleMetadata.
func (in *SimpleMetadata) DeepCopy() *SimpleMetadata {
	if in == nil {
		return nil
	}
	out := new(SimpleMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessConfig) DeepCopyInto(out *StatelessConfig) {
	*out = *in
	out.ObjectStore = in.ObjectStore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessConfig.
func (in *StatelessConfig) DeepCopy() *StatelessConfig {
	if in == nil {
		return nil
	}
	out := new(StatelessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TierSpec) DeepCopyInto(out *TierSpec) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(appsv1.RollingUpdateDeployment)
		(*in).DeepCopyInto(*out)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = (*in).DeepCopy()
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(VolumeClaimTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TierSpec.
func (in *TierSpec) DeepCopy() *TierSpec {
	if in == nil {
		return nil
	}
	out := new(TierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TierStatus) DeepCopyInto(out *TierStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TierStatus.
func (in *TierStatus) DeepCopy() *TierStatus {
	if in == nil {
		return nil
	}
	out := new(TierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tiers) DeepCopyInto(out *Tiers) {
	*out = *in
	in.Index.DeepCopyInto(&out.Index)
	in.Search.DeepCopyInto(&out.Search)
	in.ML.DeepCopyInto(&out.ML)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tiers.
func (in *Tiers) DeepCopy() *Tiers {
	if in == nil {
		return nil
	}
	out := new(Tiers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimTemplate) DeepCopyInto(out *VolumeClaimTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimTemplate.
func (in *VolumeClaimTemplate) DeepCopy() *VolumeClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimTemplate)
	in.DeepCopyInto(out)
	return out
}
