apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.2
  nodeSets:
    - name: data-zone-b
      count: 1
      config:
        node.attr.zone: europe-west1-b
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "master", "data", "ingest" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-b
    - name: data-zone-c
      count: 1
      config:
        node.attr.zone: europe-west1-c
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "master", "data", "ingest" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-c
    - name: data-zone-d
      count: 1
      config:
        node.attr.zone: europe-west1-d
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "master", "data", "ingest" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-d
    - name: ml-zone-b
      count: 1
      config:
        node.attr.zone: europe-west1-b
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "ml" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-b
    - name: ml-zone-c
      count: 1
      config:
        node.attr.zone: europe-west1-c
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "ml" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-c
    - name: ml-zone-d
      count: 1
      config:
        node.attr.zone: europe-west1-d
        cluster.routing.allocation.awareness.attributes: zone
        node.roles: [ "ml" ]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-d
  resourcePolicies:
  - roles:  [ "master", "data", "ingest" ]
    minAllowed:
      count: 1
      cpu: 1
      memory: 2G
    maxAllowed:
      count: 3
      cpu: 3
      memory: 4G
  - roles: [ "ml" ]
    minAllowed:
      count: 1
      cpu: 1
      memory: 2G
    maxAllowed:
      count: 5
      cpu: 3
      memory: 4G