apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.2
  nodeSets:
    - name: nodeset1
      config:
        node.master: true
        node.data: false
        node.ingest: false
        node.store.allow_mmap: false
      count: 3
    - name: nodeset2
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      count: 2
    - name: nodeset3
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      count: 3