# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.15.1
  nodeSets:
  - name: default
    config:
      ##############################
      # Setup allocation awareness #
      node.attr.zone: ${ZONE}
      cluster.routing.allocation.awareness.attributes: zone
      cluster.routing.allocation.awareness.force.zone.values: ${ZONES}
      ##############################
      node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-sample
                elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-sample-es-default
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ZONE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['topology.kubernetes.io/zone']
          - name: ZONES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['topology.kubernetes.io/zones']
    count: 6
